# =============================================================================
# POCKETLEDGER DOCKER COMPOSE
# =============================================================================
# Local development and testing environment
# =============================================================================

version: '3.8'

services:
  # =============================================================================
  # WEB APPLICATION
  # =============================================================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketledger-app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_STORE=database
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
      - MAIL_MAILER=log
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    networks:
      - pocketledger-network
    depends_on:
      - redis

  # =============================================================================
  # REDIS (for caching and sessions)
  # =============================================================================
  redis:
    image: redis:7-alpine
    container_name: pocketledger-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pocketledger-network

  # =============================================================================
  # MYSQL (alternative database)
  # =============================================================================
  mysql:
    image: mysql:8.0
    container_name: pocketledger-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pocketledger
      MYSQL_USER: pocketledger
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pocketledger-network
    profiles:
      - mysql

  # =============================================================================
  # POSTGRESQL (alternative database)
  # =============================================================================
  postgres:
    image: postgres:15-alpine
    container_name: pocketledger-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pocketledger
      POSTGRES_USER: pocketledger
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pocketledger-network
    profiles:
      - postgres

  # =============================================================================
  # MAILHOG (for email testing)
  # =============================================================================
  mailhog:
    image: mailhog/mailhog:latest
    container_name: pocketledger-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - pocketledger-network
    profiles:
      - mailhog

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local
  postgres_data:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  pocketledger-network:
    driver: bridge
